# This config file lists the ruby/specs that should pass for Artichoke Ruby.
#
# Valid values for `include` are:
#
# - all - run all specs. When `include` is set to `all`, the optional `skip`
#   field may list specs to skip.
# - none - run no specs, equivalent to the section not being present in this
#   config file.
# - `set` - run an enumerated set of specs. When `include` is set to `set`, the
#   set of specs must be listed in the required `specs` field, which is a list
#   of strings.

## Ruby Standard Library

[specs.library.abbrev]
include = "all"

[specs.library.base64]
include = "all"

[specs.library.delegate]
include = "none"

[specs.library.monitor]
include = "all"

[specs.library.securerandom]
include = "all"
skip = [
  # missing support for Bignum and Range arguments
  "random_number",
]

[specs.library.shellwords]
include = "all"
skip = [
  # missing `String#gsub` support for back references
  "shellwords",
]

[specs.library.stringscanner]
include = "all"

[specs.library.time]
# missing `date` package
include = "none"

[specs.library.uri]
include = "all"
skip = ["parse"]
